# Privacy-sensitive BlueMap plugin settings.
live-player-markers: false
hidden-game-modes: ["spectator"]
hide-vanished: true
hide-invisible: true
hide-sneaking: false
hide-below-sky-light: 0
hide-below-block-light: 0
hide-different-world: false

# Zero prevents markers and players being persisted into map storage.
write-markers-interval: 0
write-players-interval: 0
skin-download: false
player-render-limit: -1
