enabled: true
webroot: "bluemap/web"
update-settings-file: true
use-cookies: true
default-to-flat-view: false
start-location: "world:89:53:-106:108:2.54:1.08:0:0:perspective"
min-zoom-distance: 5
max-zoom-distance: 100000
resolution-default: 1
hires-slider-max: 500
hires-slider-default: 100
hires-slider-min: 0
lowres-slider-max: 7000
lowres-slider-default: 2000
lowres-slider-min: 500
scripts: []
styles: []
