world: "world"
dimension: "minecraft:the_nether"
name: "world (the_nether)"
sorting: 100
start-pos: { x: 0, z: 0 }
sky-color: "#290000"
void-color: "#150000"
sky-light: 1
ambient-light: 0.6
remove-caves-below-y: -10000
cave-detection-ocean-floor: -5
cave-detection-uses-block-light: false
min-inhabited-time: 0
render-mask: [
  {}
  {
    subtract: true
    min-y: 90
    max-y: 127
  }
]
render-edges: true
edge-light-strength: 8
enable-perspective-view: true
enable-flat-view: true
enable-free-flight-view: true
enable-hires: true
storage: "file"
ignore-missing-light-data: false
marker-sets: {}
